### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-lib.so" not found

### ISSUE THREAD

**Issue by aiynmm** [2016lc/FFmpegVideoPlay#3]
运行直接报错了！咋回事？

**Comment by 2016lc** [comment]
&nbsp;library "libnative-lib.so" not found&nbsp; &nbsp;libnative-lib.so没找到哎，你看看哪里copy过去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "2016lc/FFmpegVideoPlay"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月15日(星期二) 中午11:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[2016lc/FFmpegVideoPlay] java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-lib.so" not found (#3)





 
运行直接报错了！咋回事？

**Comment by aiynmm** [comment]
解决了，ffmpeg是我自己编译的，没有用你的，cpu架构有问题，换了一个就好了
